import { z } from 'zod';

export const chuVanVuongOmenSchema = z.enum([
  'dai_cat',
  'cat',
  'binh',
  'hung',
  'dai_hung',
]);

export type ChuVanVuongOmen = z.infer<typeof chuVanVuongOmenSchema>;

export const chuVanVuongTrigramSchema = z.enum([
  'can',      // Càn (Thiên - Trời)
  'doai',     // Đoài (Trạch - Đầm)
  'ly',       // Ly (Hỏa - Lửa)
  'chan',     // Chấn (Lôi - Sấm)
  'ton',      // Tốn (Phong - Gió)
  'kham',     // Khảm (Thủy - Nước)
  'can_son',  // Cấn (Sơn - Núi)
  'khon',     // Khôn (Địa - Đất)
]);

export type ChuVanVuongTrigram = z.infer<typeof chuVanVuongTrigramSchema>;

export const chuVanVuongHexagramSchema = z.object({
  id: z.number().int().min(1).max(64),
  name: z.string().min(1),
  nature: z.string().min(1),
  upperTrigram: z.string().min(1),
  lowerTrigram: z.string().min(1),
  omen: chuVanVuongOmenSchema,
  omenLabel: z.string().min(1),
  meaning: z.string().min(1),
  poem: z.string().min(1),
  advice: z.string().min(1),
  domains: z.object({
    taiLoc: z.string().min(1),
    congDanh: z.string().min(1),
    giaDao: z.string().min(1),
    sucKhoe: z.string().min(1),
  }),
});

export type ChuVanVuongHexagram = z.infer<typeof chuVanVuongHexagramSchema>;

export const CHU_VAN_VUONG_HEXAGRAMS: readonly ChuVanVuongHexagram[] = [
  {
    id: 1,
    name: 'Thuần Càn',
    nature: 'Thiên Vi Càn',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Nguyên, hanh, lợi, trinh. Thời vận hanh thông tột bực, đại hiển quang minh.',
    poem: 'Trời cao lồng lộng đức càn khôn / Rồng lượn mây bay rạng cửa môn / Đại sự vững vàng tâm chính trực / Vinh hoa phú quý thấu hoàng thôn.',
    advice: 'Thời vận cực thịnh, nên giữ tâm chính trực, khiêm hòa và bền bỉ để bảo toàn phúc đức.',
    domains: {
      taiLoc: 'Tài lộc dồi dào, đầu tư kinh doanh thu lợi lớn, có quý nhân trợ lực.',
      congDanh: 'Thăng quan tiến chức, thi cử đỗ đạt cao, uy tín vang xa.',
      giaDao: 'Gia đạo yên vui, dòng họ rạng danh, đón tin mừng hỷ sự.',
      sucKhoe: 'Khí lực sung mãn, tinh thần sảng khoái, cần chú ý nghỉ ngơi điều độ.',
    },
  },
  {
    id: 2,
    name: 'Thuần Khôn',
    nature: 'Địa Vi Khôn',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Nhu thuận bao dung, đất dày chở vật, bền lòng ắt thành tựu.',
    poem: 'Đất dày chở nặng đức bao la / Nhu thuận hòa vui khắp mọi nhà / Tiến bước từ tâm theo chính đạo / Phúc lành che chở tựa bài ca.',
    advice: 'Nên kiên nhẫn, điềm đạm, lắng nghe và hợp tác thay vì đối đầu trực diện.',
    domains: {
      taiLoc: 'Tài chính ổn định, tích lũy vững chắc, buôn bán dài lâu có lộc.',
      congDanh: 'Được cấp trên tin tưởng, đồng nghiệp ủng hộ, tiến bước tuần tự.',
      giaDao: 'Mẹ hiền con thảo, gia đình thuận hòa, phúc ấm dài lâu.',
      sucKhoe: 'Cần bồi bổ tỳ vị, ăn uống điều độ, tránh lao lực quá sức.',
    },
  },
  {
    id: 3,
    name: 'Thủy Lôi Truân',
    nature: 'Thủy Lôi Truân',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Vạn vật mới sinh còn non nớt, khởi đầu gian nan cần kiên trì gầy dựng.',
    poem: 'Hạt mầm đội đất đón mưa sương / Vạn sự sơ khai dẫu trắc trường / Vững chí bền gan xây nghiệp lớn / Mai này hoa nở ngát ngàn phương.',
    advice: 'Không nên vội vã mở rộng, hãy tích lũy kinh nghiệm và củng cố nền tảng.',
    domains: {
      taiLoc: 'Tiền bạc chưa dồi dào, cần thắt chặt chi tiêu, tránh mạo hiểm.',
      congDanh: 'Bước đầu khó khăn, cần nỗ lực học hỏi, chờ thời cơ thuận lợi.',
      giaDao: 'Có chút bất đồng nhỏ, cần kiên nhẫn giải thích để thấu hiểu.',
      sucKhoe: 'Đề phòng cảm lạnh, mệt mỏi do lo toan thời kỳ đầu.',
    },
  },
  {
    id: 4,
    name: 'Sơn Thủy Mông',
    nature: 'Sơn Thủy Mông',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Mờ mịt như sương dưới chân núi, cần tìm thầy học đạo, khai sáng trí tuệ.',
    poem: 'Chân núi sương mờ lối khuất che / Tìm thầy học hỏi sớm trưa nghe / Tâm trong sáng tỏ đường quang đãng / Thuận lối hanh thông dẫu cách bè.',
    advice: 'Hạ mình thỉnh giáo bậc tiền bối, lắng nghe lời khuyên chân thành.',
    domains: {
      taiLoc: 'Chưa rõ ràng, chớ vội đầu tư vào lĩnh vực bản thân chưa thấu đáo.',
      congDanh: 'Nên trau dồi chuyên môn, thi cử cần ôn luyện kỹ càng.',
      giaDao: 'Cần kiên nhẫn uốn nắn con trẻ, tránh nóng vội gắt gỏng.',
      sucKhoe: 'Căng thẳng tinh thần, cần tĩnh tâm và thư giãn điều độ.',
    },
  },
  {
    id: 5,
    name: 'Thủy Thiên Nhu',
    nature: 'Thủy Thiên Nhu',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Chờ đợi thời cơ, mưa rào trên trời sắp tưới mát ruộng cày.',
    poem: 'Mây đượm trên trời đợi giọt mưa / Kiên tâm chờ vận chớ say sưa / Trà thơm rượu quý lòng thanh thản / Cơ hội bừng lên nối nghiệp xưa.',
    advice: 'Bình tĩnh chờ đợi, giữ gìn sức lực và chuẩn bị sẵn sàng khi vận hội đến.',
    domains: {
      taiLoc: 'Sắp có nguồn thu mới, tạm thời duy trì nguồn vốn sẵn có.',
      congDanh: 'Cơ hội thăng tiến đang tới gần, hãy thể hiện năng lực đúng thời điểm.',
      giaDao: 'Mọi việc dần ổn định, tiệc tùng gặp gỡ người thân ấm cúng.',
      sucKhoe: 'Ăn uống bồi dưỡng thể chất, giữ tinh thần lạc quan.',
    },
  },
  {
    id: 6,
    name: 'Thiên Thủy Tụng',
    nature: 'Thiên Thủy Tụng',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Bất đồng tranh chấp, trời đi lên nước chảy xuống, cần dĩ hòa vi quý.',
    poem: 'Trời lên nước xuống ngược chiều nhau / Tranh cãi hơn thua chuốc nỗi sầu / Nhường nhịn ba phân lòng tự tại / Hòa vi quý trọng dứt lo âu.',
    advice: 'Tránh tranh chấp, kiện tụng; chủ động hòa giải và nhường nhịn để giữ bình yên.',
    domains: {
      taiLoc: 'Dễ hao tài vì tranh chấp hoặc vi phạm hợp đồng, cần minh bạch.',
      congDanh: 'Dễ vướng thị phi, bất đồng với cấp trên hoặc đối tác.',
      giaDao: 'Vợ chồng lời qua tiếng lại, cần kiềm chế lời nói lúc giận hờn.',
      sucKhoe: 'Khí huyết không thông, đau đầu do căng thẳng tranh cãi.',
    },
  },
  {
    id: 7,
    name: 'Địa Thủy Sư',
    nature: 'Địa Thủy Sư',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Nước ẩn trong lòng đất, tập hợp lực lượng, kỷ luật nghiêm minh xuất trận.',
    poem: 'Đất chở nguồn sông tụ nghĩa quân / Kỷ cương phép nước giữ lòng nhân / Danh sư chính trực điều muôn sự / Vạn dặm bình yên rạng thế trần.',
    advice: 'Hành động có tổ chức, tuân thủ nguyên tắc kỷ luật, chọn người tài giao việc.',
    domains: {
      taiLoc: 'Cần quản lý tài chính chặt chẽ, chi tiêu theo kế hoạch định sẵn.',
      congDanh: 'Được giao trọng trách lãnh đạo, cần thưởng phạt công minh.',
      giaDao: 'Gia phong kỷ cương, tôn ti trật tự rõ ràng thì gia đạo hưng thịnh.',
      sucKhoe: 'Cần rèn luyện thể thao, tăng cường thể lực chống suy nhược.',
    },
  },
  {
    id: 8,
    name: 'Thủy Địa Tỷ',
    nature: 'Thủy Địa Tỷ',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Nước thấm vào đất, thân mật gắn kết, kết giao chân tình cùng phát triển.',
    poem: 'Nước nhuần lòng đất thắm duyên xưa / Bằng hữu tương giao sớm lại trưa / Chung sức một lòng xây nghiệp thịnh / Phúc lành chan chứa tựa mùa mưa.',
    advice: 'Chủ động xây dựng quan hệ tốt đẹp, trung thực và nhiệt tình giúp đỡ người khác.',
    domains: {
      taiLoc: 'Hợp tác làm ăn thuận lợi, đối tác đáng tin cậy mang lại lợi nhuận.',
      congDanh: 'Được đồng nghiệp và cấp trên quý mến, cơ hội thăng tiến mở rộng.',
      giaDao: 'Hòa thuận ấm êm, xóm giềng tương trợ, đón khách quý phương xa.',
      sucKhoe: 'Sức khỏe ổn định, tâm trạng an vui thoải mái.',
    },
  },
  {
    id: 9,
    name: 'Phong Thiên Tiểu Súc',
    nature: 'Phong Thiên Tiểu Súc',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Gió thổi trên trời mây tụ chưa mưa, tích lũy điều nhỏ chờ vận lớn.',
    poem: 'Mây dày gió thoảng chửa mưa mau / Tích lũy điều con đượm sắc màu / Khéo léo giữ gìn từng mối nhỏ / Chờ ngày sấm dậy hóa rồng sâu.',
    advice: 'Kiên trì tích lũy từng bước nhỏ, chớ nôn nóng làm việc quá sức.',
    domains: {
      taiLoc: 'Tiền tài tích lũy chậm mà chắc, không nên đầu tư mạo hiểm lớn.',
      congDanh: 'Từng bước khẳng định năng lực, chờ cơ hội tốt hơn để bứt phá.',
      giaDao: 'Cần chú ý những mâu thuẫn nhỏ thường ngày để sớm hóa giải.',
      sucKhoe: 'Chú ý bệnh đường hô hấp, tránh nơi gió lạnh.',
    },
  },
  {
    id: 10,
    name: 'Thiên Trạch Lý',
    nature: 'Thiên Trạch Lý',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Đi trên đuôi cọp mà cọp không cắn, giữ lễ nghĩa chừng mực thì chuyển nguy thành an.',
    poem: 'Bén gót hùm thiêng chớ hãi kinh / Giữ tròn lễ nghĩa vẹn ân tình / Khiêm cung cẩn trọng từng đường bước / Bình định tai ương rạng thái bình.',
    advice: 'Cẩn trọng trong từng lời nói việc làm, tôn trọng cấp trên và lễ nghi xã giao.',
    domains: {
      taiLoc: 'Lợi nhuận có được từ sự thận trọng và giữ chữ tín.',
      congDanh: 'Vượt qua thử thách khó khăn nhờ ứng xử khéo léo và đúng mực.',
      giaDao: 'Kính trên nhường dưới, gia đình hòa mục êm ấm.',
      sucKhoe: 'Cẩn thận khi đi lại xe cộ, giữ gìn chân tay.',
    },
  },
  {
    id: 11,
    name: 'Địa Thiên Thái',
    nature: 'Địa Thiên Thái',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Trời đất giao hòa, âm dương tương thông, vạn vật hanh thông thái bình.',
    poem: 'Khí trời đất thắm tựa mùa xuân / Phúc lộc tràn trề rạng thế nhân / Kẻ xấu lùi xa người tốt đến / Cơ đồ xán lạn sáng muôn phần.',
    advice: 'Thời vận cực tốt, hãy mạnh dạn nắm bắt cơ hội và san sẻ may mắn với mọi người.',
    domains: {
      taiLoc: 'Tài chính hanh thông vượt bậc, buôn may bán đắt, thu hoạch lớn.',
      congDanh: 'Đạt đỉnh cao sự nghiệp, được công nhận và thăng thưởng xứng đáng.',
      giaDao: 'Trăm năm hòa hợp, con cháu hiếu thuận, hỷ sự liên miên.',
      sucKhoe: 'Khỏe mạnh an khang, tràn đầy sinh lực.',
    },
  },
  {
    id: 12,
    name: 'Thiên Địa Bĩ',
    nature: 'Thiên Địa Bĩ',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Trời đất cách trở, âm dương không thông, thời vận bế tắc cần ẩn nhẫn.',
    poem: 'Trời đất xa xôi chẳng thuận dòng / Việc đời bế tắc luống hoài công / Giữ mình trong sạch chờ qua hạn / Chớ vội đua chen chốn bụi hồng.',
    advice: 'Nên phòng thủ, giữ gìn tài sản, bảo vệ bản thân và chờ đợi thời thế đổi thay.',
    domains: {
      taiLoc: 'Thất thoát tiền của, chớ cho vay mượn hay đầu cơ lúc này.',
      congDanh: 'Bị cản trở, khó phát huy năng lực, nên trau dồi nội lực âm thầm.',
      giaDao: 'Lạnh nhạt xa cách, thiếu sự chia sẻ giữa các thành viên.',
      sucKhoe: 'Cần khám sức khỏe định kỳ, đề phòng bệnh mãn tính tái phát.',
    },
  },
  {
    id: 13,
    name: 'Thiên Hỏa Đồng Nhân',
    nature: 'Thiên Hỏa Đồng Nhân',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Cùng chung chí hướng, lửa hướng lên trời, kết giao bằng hữu đại nghĩa.',
    poem: 'Lửa sáng soi trời dạ sắt son / Đồng tâm hiệp lực vững như non / Đường xa mở lối muôn bè bạn / Nghiệp cả vinh hoa sáng nước non.',
    advice: 'Mở rộng giao lưu, tìm kiếm cộng sự chung chí hướng để hợp tác phát triển.',
    domains: {
      taiLoc: 'Kinh doanh cộng tác phát đạt, có bạn bè mang lại cơ hội kiếm tiền.',
      congDanh: 'Được tập thể tín nhiệm đề bạt, xây dựng đội ngũ vững mạnh.',
      giaDao: 'Bằng hữu sum vầy, gia đạo hòa nhã, có duyên kết giao quý tộc.',
      sucKhoe: 'Nhiệt huyết dồi dào, cần tránh thức khuya làm việc quá sức.',
    },
  },
  {
    id: 14,
    name: 'Hỏa Thiên Đại Hữu',
    nature: 'Hỏa Thiên Đại Hữu',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Mặt trời tỏa sáng giữa ban trưa, mùa màng bội thu, sở hữu phong phú.',
    poem: 'Mặt trời rực rỡ giữa trời cao / Tài lộc muôn phương chảy rạt rào / Đức độ soi chung cùng thiên hạ / Bốn mùa no ấm vạn niềm khao.',
    advice: 'Thành công vang dội, nên hành thiện tích đức để phúc lộc được trường tồn.',
    domains: {
      taiLoc: 'Tài chính sung túc dồi dào, thu nhập tăng vọt, của cải dôi dư.',
      congDanh: 'Danh tiếng lẫy lừng, đạt được mục tiêu lớn đã ấp ủ từ lâu.',
      giaDao: 'Gia đình thịnh vượng, con cái thành đạt, rạng rỡ gia phong.',
      sucKhoe: 'Sinh lực tràn trề, phòng tránh các bệnh nóng nhiệt.',
    },
  },
  {
    id: 15,
    name: 'Địa Sơn Khiêm',
    nature: 'Địa Sơn Khiêm',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Núi cao nằm dưới đất bằng, khiêm nhường nhún nhường thì được quỷ thần phù hộ.',
    poem: 'Núi giấu trong lòng đất rộng sâu / Khiêm nhường nhún bước dẫu đi đầu / Người khen quỷ phục trời thương mến / Hưởng trọn an nhiên dứt mối sầu.',
    advice: 'Luôn giữ thái độ khiêm tốn, biết lắng nghe, không kiêu căng tự phụ.',
    domains: {
      taiLoc: 'Tiền bạc vào đều đặn, không bị người khác ghen ghét dòm ngó.',
      congDanh: 'Càng nhún nhường càng được trọng dụng và nể phục thực sự.',
      giaDao: 'Gia đình êm ấm trên thuận dưới hòa, hàng xóm yêu mến.',
      sucKhoe: 'Tâm an thì thân khỏe, ngủ ngon giấc, ít lo toan.',
    },
  },
  {
    id: 16,
    name: 'Lôi Địa Dự',
    nature: 'Lôi Địa Dự',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Sấm động trên mặt đất mùa xuân, vui vẻ phấn khởi, chuẩn bị ra quân.',
    poem: 'Sấm vang lay động khắp đồng xanh / Vạn vật hân hoan rộn sắc lành / Chuẩn bị chu toàn khai vận mới / Tiếng cười vang vọng thỏa lòng anh.',
    advice: 'Tận hưởng niềm vui nhưng không sa đà, chuẩn bị kỹ lưỡng kế hoạch tiếp theo.',
    domains: {
      taiLoc: 'Có nguồn thu bất ngờ, tiền thưởng hoặc quà tặng may mắn.',
      congDanh: 'Không khí làm việc phấn khởi, dự án khởi động thuận lợi.',
      giaDao: 'Có tiệc mừng, đón tin vui từ người thân, gia đình rộn rã tiếng cười.',
      sucKhoe: 'Tinh thần phấn chấn, cần duy trì lối sống lành mạnh.',
    },
  },
  {
    id: 17,
    name: 'Trạch Lôi Tùy',
    nature: 'Trạch Lôi Tùy',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Sấm ẩn trong đầm, tùy cơ ứng biến, thuận theo dòng chảy cuộc đời.',
    poem: 'Thuận dòng nước chảy thả buồm xuôi / Tùy biến theo thời dạ chẳng nguôi / Gặp việc ứng duyên lòng thanh thản / Hưởng trọn bình an vạn nụ cười.',
    advice: 'Biết tùy cơ ứng biến, không cố chấp, linh hoạt thay đổi theo hoàn cảnh.',
    domains: {
      taiLoc: 'Linh hoạt nắm bắt xu hướng thị trường để kiếm thêm thu nhập.',
      congDanh: 'Biết hòa nhập và thích nghi nhanh với môi trường mới.',
      giaDao: 'Tôn trọng ý kiến của nhau, gia đình vui vẻ thuận hòa.',
      sucKhoe: 'Nghỉ ngơi theo đồng hồ sinh học, thích nghi thời tiết.',
    },
  },
  {
    id: 18,
    name: 'Sơn Phong Cổ',
    nature: 'Sơn Phong Cổ',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Gió nghẽn dưới chân núi sinh hư hoại, cần can đảm sửa chữa tàn tích.',
    poem: 'Gió nghẽn chân non mọt rũa ngầm / Phải lo sửa chữa tự đáy tâm / Trừ gian dẹp xấu xây nề mới / Trùng hưng cơ nghiệp sáng vạn năm.',
    advice: 'Dũng cảm đối mặt với sai lầm cũ, tái cấu trúc và sửa chữa kịp thời.',
    domains: {
      taiLoc: 'Cần kiểm toán lại sổ sách, phát hiện và cắt giảm các khoản chi lãng phí.',
      congDanh: 'Phải giải quyết dứt điểm các tồn đọng công việc trước khi làm việc mới.',
      giaDao: 'Hàn gắn các khúc mắc cũ giữa người thân trong gia đình.',
      sucKhoe: 'Cần thanh lọc cơ thể, giải độc, kiểm tra đường tiêu hóa.',
    },
  },
  {
    id: 19,
    name: 'Địa Trạch Lâm',
    nature: 'Địa Trạch Lâm',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Đất bao bọc đầm nước, thế nước dâng cao, phúc lộc tiến đến trước thềm.',
    poem: 'Đất ôm đầm biếc nước triều dâng / Vận tốt vừa sang vạn sự mừng / Cần mẫn vun bồi công đức sáng / Cơ đồ rực rỡ bước không ngừng.',
    advice: 'Thời vận đang lên, nên tận dụng thời gian để hoàn thành việc lớn.',
    domains: {
      taiLoc: 'Kinh doanh phát đạt, khách hàng tìm đến đông đảo.',
      congDanh: 'Cơ hội thăng tiến mở ra, được giao thêm quyền hạn và trọng trách.',
      giaDao: 'Có tin mừng về con cái, thêm người thêm của.',
      sucKhoe: 'Khỏe mạnh, sinh lực dồi dào.',
    },
  },
  {
    id: 20,
    name: 'Phong Địa Quan',
    nature: 'Phong Địa Quan',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Gió thổi lướt trên mặt đất, quan sát chiêm nghiệm, làm gương cho đời.',
    poem: 'Gió lướt đồng hoang thấu sự đời / Ngắm nhìn muôn dặm chốn trần khơi / Lắng lòng soi chiếu tâm thanh tịnh / Đợi đón thời cơ chuyển vận thời.',
    advice: 'Lắng đọng quan sát, đánh giá tình hình tổng thể trước khi đưa ra quyết định.',
    domains: {
      taiLoc: 'Chưa nên giải ngân lớn, quan sát biến động thị trường trước.',
      congDanh: 'Nên giữ vai trò cố vấn, giám sát, học hỏi thêm kỹ năng quản trị.',
      giaDao: 'Làm gương mẫu mực cho con cháu noi theo.',
      sucKhoe: 'Dưỡng mắt và thần kinh, tránh xem màn hình điện tử quá nhiều.',
    },
  },
  {
    id: 21,
    name: 'Hỏa Lôi Phệ Hạp',
    nature: 'Hỏa Lôi Phệ Hạp',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Cắn đứt chướng ngại, dùng pháp luật công minh để trừ gian xảo.',
    poem: 'Sấm nổ lửa soi cắn dứt rào / Công minh chính trực vững ngôi cao / Xua tan gian dối trừ hung hiểm / Đem lại yên bình tựa gấm đào.',
    advice: 'Quyết đoán xử lý chướng ngại, dùng lẽ phải và công bằng để phân xử.',
    domains: {
      taiLoc: 'Cần giải quyết nợ nần dứt điểm, rõ ràng tiền bạc với đối tác.',
      congDanh: 'Vượt qua cạnh tranh bằng năng lực thực tế và sự cương trực.',
      giaDao: 'Thẳng thắn giải quyết bất đồng, không để uất ức kéo dài.',
      sucKhoe: 'Chú ý răng miệng và vùng họng, tránh viêm nhiễm.',
    },
  },
  {
    id: 22,
    name: 'Sơn Hỏa Bí',
    nature: 'Sơn Hỏa Bí',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Lửa chiếu sáng chân núi, văn vẻ tươi đẹp, chuộng sự giản dị tự nhiên.',
    poem: 'Núi sáng ánh hồng vẻ thắm tươi / Văn hoa lễ nghĩa rạng môi cười / Tô bồi nét đẹp từ tâm khảm / Mộc mạc chân tình sưởi ấm người.',
    advice: 'Chú trọng hình thức lịch sự nhưng cốt lõi vẫn là thực chất bên trong.',
    domains: {
      taiLoc: 'Thích hợp cho ngành nghề nghệ thuật, truyền thông, làm đẹp.',
      congDanh: 'Khẳng định uy tín qua cách đối nhân xử thế văn nhã.',
      giaDao: 'Trang hoàng nhà cửa ấm cúng, đón khách quý đến chơi.',
      sucKhoe: 'Chăm sóc làn da và sắc diện, giữ tinh thần thư thái.',
    },
  },
  {
    id: 23,
    name: 'Sơn Địa Bác',
    nature: 'Sơn Địa Bác',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Núi lở mòn dần xuống đất, tiểu nhân lấn át quân tử, cần án binh bất động.',
    poem: 'Mưa dập non cao đá lở mòn / Thời cơ chưa đến phải lo bòn / Giữ gìn khí tiết qua cơn bão / Chờ đón dương quang rạng nước non.',
    advice: 'Không nên manh động hay mở rộng kinh doanh, bảo toàn vốn liếng là thượng sách.',
    domains: {
      taiLoc: 'Nguy cơ mất tiền, hao hụt tài sản, tuyệt đối không cho vay tiền.',
      congDanh: 'Tránh đối đầu với kẻ tiểu nhân ganh ghét, nhẫn nhịn giữ vị trí.',
      giaDao: 'Gia đạo có nguy cơ xáo trộn, cần bình tĩnh gắn kết.',
      sucKhoe: 'Xương khớp yếu, cẩn thận vấp ngã khi đi lại.',
    },
  },
  {
    id: 24,
    name: 'Địa Lôi Phục',
    nature: 'Địa Lôi Phục',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Dương khí quay trở lại dưới lòng đất, mùa đông tàn xuân đến, chu kỳ mới bắt đầu.',
    poem: 'Sấm chuyển trong lòng đất lạnh đông / Mầm xuân hé nụ trổ cành hồng / Vận suy đã dứt niềm vui lại / Thong thả thuyền xuôi rạng bến sông.',
    advice: 'Khởi đầu lại từ những việc nhỏ, kiên nhẫn xây dựng từng bước một.',
    domains: {
      taiLoc: 'Tài vận bắt đầu hồi phục, có tín hiệu kinh doanh khả quan.',
      congDanh: 'Tìm lại cơ hội sau giai đoạn khó khăn, bước đầu hanh thông.',
      giaDao: 'Hàn gắn tình cảm, người đi xa quay về đoàn tụ.',
      sucKhoe: 'Bệnh tật thuyên giảm, sức lực dần hồi sinh.',
    },
  },
  {
    id: 25,
    name: 'Thiên Lôi Vô Vọng',
    nature: 'Thiên Lôi Vô Vọng',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Làm theo lẽ tự nhiên, không toan tính gian dối, chân thành ắt vô sự.',
    poem: 'Sấm gầm trời thẳm luật công minh / Giữ vẹn lòng son trọn chữ tình / Chớ mộng làm liều vương tai họa / Cứ theo thiên đạo đặng an sinh.',
    advice: 'Làm việc theo đúng lương tâm và quy luật, không tham lam của bất chính.',
    domains: {
      taiLoc: 'Kiếm tiền bằng sức lao động chân chính, tránh cờ bạc may rủi.',
      congDanh: 'Tập trung vào nhiệm vụ của mình, chớ mưu mô tranh đoạt.',
      giaDao: 'Chân thành đối xử với người nhà, không giấu giếm gian dối.',
      sucKhoe: 'Đề phòng tai bay vạ gió bất ngờ, cẩn thận khi ra ngoài.',
    },
  },
  {
    id: 26,
    name: 'Sơn Thiên Đại Súc',
    nature: 'Sơn Thiên Đại Súc',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Trời chứa trong lòng núi, tích lũy kiến thức và tài đức sâu dày.',
    poem: 'Núi chứa trời cao đức rộng dày / Bao năm tôi luyện đặng hôm nay / Tài danh chất chứa nuôi bờ cõi / Xuất trận thành công nắm chắc tay.',
    advice: 'Đã tích lũy đủ nội lực, hãy tự tin triển khai kế hoạch lớn.',
    domains: {
      taiLoc: 'Tài chính vững mạnh, tích lũy dồi dào, chuẩn bị đầu tư lớn.',
      congDanh: 'Được công nhận tài năng xuất chúng, giữ trọng trách lớn.',
      giaDao: 'Nền tảng gia phong vững chắc, con cái học hành thành đạt.',
      sucKhoe: 'Thể lực sung mãn, dẻo dai và bền bỉ.',
    },
  },
  {
    id: 27,
    name: 'Sơn Lôi Di',
    nature: 'Sơn Lôi Di',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Nuôi dưỡng thân tâm, cẩn trọng lời nói và miếng ăn thức uống.',
    poem: 'Lời nói ăn vào tựa miệng rồng / Giữ gìn nết hạnh giữ lòng trong / Nuôi thân dưỡng trí tâm thanh thản / Bốn bể an vui thỏa ước mong.',
    advice: 'Cẩn trọng lời ăn tiếng nói, chú ý chế độ dinh dưỡng và tu dưỡng tâm tính.',
    domains: {
      taiLoc: 'Tự cung tự cấp tốt, chi tiêu hợp lý cho nhu cầu thiết yếu.',
      congDanh: 'Nên trau dồi kỹ năng giao tiếp, tránh phát ngôn bất cẩn.',
      giaDao: 'Bữa cơm gia đình ấm cúng, quan tâm chăm sóc sức khỏe người thân.',
      sucKhoe: 'Đặc biệt lưu ý an toàn thực phẩm, tránh ngộ độc tiêu hóa.',
    },
  },
  {
    id: 28,
    name: 'Trạch Phong Đại Quá',
    nature: 'Trạch Phong Đại Quá',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Cột nhà uốn cong vì gánh nặng quá sức, cần san sẻ bớt gánh nặng.',
    poem: 'Đầm dâng ngập gió cột cong oằn / Gánh nặng vai mang vạn nỗi băn / Cần kíp sẻ chia người trợ lực / Chớ liều ôm trọn chuốc gian truân.',
    advice: 'Không nên gồng gánh việc quá sức mình, hãy tìm người san sẻ và hỗ trợ.',
    domains: {
      taiLoc: 'Áp lực tài chính hoặc nợ nần đè nặng, cần cơ cấu lại gấp.',
      congDanh: 'Khối lượng công việc quá tải, dễ dẫn đến kiệt sức hoặc sai sót.',
      giaDao: 'Gia đình có biến cố lớn, cần mọi người chung tay gánh vác.',
      sucKhoe: 'Kiệt sức vì căng thẳng thần kinh, cần nghỉ ngơi cấp tốc.',
    },
  },
  {
    id: 29,
    name: 'Thuần Khảm',
    nature: 'Khảm Vi Thủy',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Trùng trùng hiểm trở, như vực sâu nối vực sâu, cần giữ lòng chí thành.',
    poem: 'Nước xoáy dòng sâu hiểm dặm trường / Vững lòng son sắt chớ hoang mang / Chèo qua thác lũ tâm không đổi / Cập bến bình yên rạng ánh vàng.',
    advice: 'Giữ vững niềm tin, không nao núng trước khó khăn, từng bước vượt thác ghềnh.',
    domains: {
      taiLoc: 'Nguy cơ cạn kiệt dòng tiền, cần thắt lưng buộc bụng.',
      congDanh: 'Gặp trở ngại liên tiếp, cần kiên trì không bỏ cuộc.',
      giaDao: 'Nhiều lo âu muộn phiền, cần các thành viên thấu hiểu nâng đỡ nhau.',
      sucKhoe: 'Chú ý bệnh về thận, bàng quang, hệ bài tiết và tai nạn sông nước.',
    },
  },
  {
    id: 30,
    name: 'Thuần Ly',
    nature: 'Ly Vi Hỏa',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Ánh lửa đôi chiếu sáng rực rỡ, nương tựa vào điều chính đạo.',
    poem: 'Lửa sáng lung linh chiếu rạng ngời / Nương vào chính đạo sống thảnh thơi / Tâm trong trí sáng muôn người mến / Hạnh phúc tràn trề nở khắp nơi.',
    advice: 'Nương tựa vào môi trường tốt, học tập người tài đức, giữ tâm sáng suốt.',
    domains: {
      taiLoc: 'Tài chính sáng sủa, kinh doanh các ngành đòi hỏi sự sáng tạo thu lợi nhuận.',
      congDanh: 'Tỏa sáng, được công nhận năng lực và đánh giá cao.',
      giaDao: 'Gia đình rạng rỡ, tình cảm nồng ấm yêu thương.',
      sucKhoe: 'Chú ý bệnh về tim mạch, huyết áp và mắt.',
    },
  },
  {
    id: 31,
    name: 'Trạch Sơn Hàm',
    nature: 'Trạch Sơn Hàm',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Đầm trên núi, cảm ứng tương giao, trai gái phải lòng nhau thuận thành.',
    poem: 'Đầm biếc đầu non bóng nguyệt soi / Tơ duyên cảm ứng thấu muôn lời / Lòng thành kết nối ngàn muôn dặm / Hạnh phúc trăm năm trọn kiếp đời.',
    advice: 'Chân thành trong các mối quan hệ, cảm thông và thấu hiểu người khác.',
    domains: {
      taiLoc: 'Được đối tác quý mến ủng hộ, nguồn tiền vào thuận lợi.',
      congDanh: 'Tạo được thiện cảm tốt đẹp với đối tác và cấp trên.',
      giaDao: 'Tình duyên đại cát, hôn nhân hòa hợp, đơm hoa kết trái.',
      sucKhoe: 'Sức khỏe dồi dào, tinh thần phơi phới yêu đời.',
    },
  },
  {
    id: 32,
    name: 'Lôi Phong Hằng',
    nature: 'Lôi Phong Hằng',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Sấm và gió tương trợ dài lâu, kiên trì giữ vững con đường đúng đắn.',
    poem: 'Sấm động cùng phong chuyển tháng ngày / Bền gan sắt đá dựng đời hay / Kiên tâm vững chí qua giông bão / Phúc ấm ngàn sau đọng chốn này.',
    advice: 'Giữ vững mục tiêu dài hạn, không thay đổi xoành xoạch theo cảm xúc.',
    domains: {
      taiLoc: 'Thu nhập ổn định và tăng trưởng bền vững theo thời gian.',
      congDanh: 'Gắn bó với nghề nghiệp sẽ gặt hái thành tựu lớn.',
      giaDao: 'Vợ chồng son sắt thủy chung, gia đạo bình yên lâu dài.',
      sucKhoe: 'Cần duy trì tập luyện thể thao đều đặn mỗi ngày.',
    },
  },
  {
    id: 33,
    name: 'Thiên Sơn Độn',
    nature: 'Thiên Sơn Độn',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Núi lùi xa dưới trời, thời thế bất lợi nên lui về ẩn nhẫn giữ mình.',
    poem: 'Trời cao núi khuất bóng hoàng hôn / Rút bước lui chân giữ lấy hồn / Tránh chốn thị phi cầu chữ nhẫn / Bảo toàn khí tiết đặng trường tồn.',
    advice: 'Biết rút lui đúng lúc, tránh xa các cuộc tranh chấp vô bổ.',
    domains: {
      taiLoc: 'Giữ chặt hầu bao, tránh mạo hiểm chi tiêu vào lúc này.',
      congDanh: 'Chưa nên tranh giành chức vụ, nên tạm thời lùi lại phía sau.',
      giaDao: 'Nên đi du lịch nghỉ dưỡng cùng gia đình để xả căng thẳng.',
      sucKhoe: 'Cần nghỉ ngơi tĩnh dưỡng, tránh lao tâm khổ tứ.',
    },
  },
  {
    id: 34,
    name: 'Lôi Thiên Đại Tráng',
    nature: 'Lôi Thiên Đại Tráng',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Sấm nổ vang trời, thế lực mạnh mẽ, chớ cậy sức mà húc bờ dậu.',
    poem: 'Sấm rền dậy đất khí dương cương / Sức mạnh ngàn cân trải khắp đường / Chớ cậy hùng tâm làm việc quấy / Giữ gìn phép tắc mới an khương.',
    advice: 'Dùng sức mạnh vào việc chính đáng, tránh kiêu căng tự phụ dẫn đến sai lầm.',
    domains: {
      taiLoc: 'Tài chính dồi dào, có sức mạnh đàm phán hợp đồng lớn.',
      congDanh: 'Vị thế vững vàng, có tầm ảnh hưởng lớn trong tổ chức.',
      giaDao: 'Cần kiềm chế tính nóng nảy trong gia đình.',
      sucKhoe: 'Khí huyết vượng, chú ý huyết áp và giảm ăn đồ cay nóng.',
    },
  },
  {
    id: 35,
    name: 'Hỏa Địa Tấn',
    nature: 'Hỏa Địa Tấn',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Mặt trời mọc trên mặt đất, ánh sáng chan hòa, được ban thưởng ngọc ngà.',
    poem: 'Mặt trời chiếu rọi khắp đồng xanh / Rạng rỡ thăng hoa vạn sự lành / Chúa thưởng tôi trung ban gấm vóc / Rạng ngời danh giá thỏa lòng anh.',
    advice: 'Tận dụng sự ủng hộ của cấp trên và quý nhân để tiến bước mạnh mẽ.',
    domains: {
      taiLoc: 'Được tăng lương, khen thưởng, lợi nhuận tăng trưởng ngoạn mục.',
      congDanh: 'Thăng quan tiến chức nhanh chóng, được tín nhiệm tối đa.',
      giaDao: 'Gia đình rạng danh, họ hàng chung vui chúc mừng.',
      sucKhoe: 'Sức khỏe tuyệt hảo, tinh thần phấn chấn.',
    },
  },
  {
    id: 36,
    name: 'Địa Hỏa Minh Di',
    nature: 'Địa Hỏa Minh Di',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Mặt trời lặn vào lòng đất, ánh sáng bị thương tổn, cần giấu kín tài năng.',
    poem: 'Ánh dương chìm khuất dạ mông lung / Nhẫn nhục qua cơn nghịch cảnh cùng / Khéo giấu tài ba chờ sáng lại / Tròn lòng trung nghĩa giữ kiên trung.',
    advice: 'Khiêm nhường che giấu năng lực, không nổi bật để tránh tai họa đố kỵ.',
    domains: {
      taiLoc: 'Đề phòng bị lừa gạt tiền bạc, tránh khoe khoang của cải.',
      congDanh: 'Bị ganh ghét chèn ép, nên nhẫn nại làm tốt việc phận sự.',
      giaDao: 'Có nỗi buồn giấu kín, cần cảm thông và động viên nhau.',
      sucKhoe: 'Đề phòng bệnh về mắt, tim mạch và chấn thương thể chất.',
    },
  },
  {
    id: 37,
    name: 'Phong Hỏa Gia Nhân',
    nature: 'Phong Hỏa Gia Nhân',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Gió sinh từ lửa, trong ấm ngoài êm, đạo trị nhà nề nếp yêu thương.',
    poem: 'Bếp hồng lửa ấm gió hòa êm / Nề nếp gia phong sáng trước thềm / Vợ thảo chồng hiền con hiếu thuận / Phúc lành chan chứa mãi ngày đêm.',
    advice: 'Chăm lo cho tổ ấm gia đình, lời nói việc làm chuẩn mực làm gương.',
    domains: {
      taiLoc: 'Kinh tế gia đình vững vàng, tích lũy tốt cho tương lai con cái.',
      congDanh: 'Hậu phương vững chắc giúp sự nghiệp thăng hoa.',
      giaDao: 'Gia đạo hưng vượng, thuận vợ thuận chồng tát biển Đông cũng cạn.',
      sucKhoe: 'Mọi người trong nhà đều khỏe mạnh an vui.',
    },
  },
  {
    id: 38,
    name: 'Hỏa Trạch Khuê',
    nature: 'Hỏa Trạch Khuê',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Lửa bốc lên cao đầm chảy xuống thấp, trái ngược chia rẽ, bất đồng quan điểm.',
    poem: 'Lửa bốc lên cao nước chảy xuôi / Trái đường nghịch lối dạ khôn nguôi / Tìm điểm tương đồng hòa giải khúc / Mới mong tìm lại vẹn niềm vui.',
    advice: 'Tôn trọng sự khác biệt, tìm kiếm điểm chung để hợp tác và tránh đổ vỡ.',
    domains: {
      taiLoc: 'Dễ xảy ra tranh cãi về phân chia lợi nhuận, cần hợp đồng rõ ràng.',
      congDanh: 'Bất đồng quan điểm với đồng nghiệp, dự án dễ bị chậm trễ.',
      giaDao: 'Hiểu lầm xích mích giữa các thành viên, cần ngồi lại nói chuyện.',
      sucKhoe: 'Nóng trong người, bốc hỏa, nổi mụn nhọt, cần giải nhiệt.',
    },
  },
  {
    id: 39,
    name: 'Thủy Sơn Kiển',
    nature: 'Thủy Sơn Kiển',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Trước núi sau vực sâu, đường đi hiểm trở khó khăn, nên dừng lại tìm lối.',
    poem: 'Trước núi che ngang sau vực sâu / Gian nan trắc trở nối lo âu / Dừng chân ngẫm lại tìm mưu kế / Chờ đón hanh thông giải nỗi sầu.',
    advice: 'Dừng lại quan sát, không nên cố chấp tiến bước vào nơi nguy hiểm.',
    domains: {
      taiLoc: 'Bế tắc tài chính tạm thời, không nên vay nóng hay đầu tư liều.',
      congDanh: 'Công việc gặp trắc trở lớn, cần sự trợ giúp từ bên ngoài.',
      giaDao: 'Gặp chuyện khó khăn cần các thành viên cùng chung vai gánh vác.',
      sucKhoe: 'Chú ý chân tay, đau nhức khớp, hạn chế leo trèo nguy hiểm.',
    },
  },
  {
    id: 40,
    name: 'Lôi Thủy Giải',
    nature: 'Lôi Thủy Giải',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Mưa rào sấm nổ tan biến bức bối, khó khăn được tháo gỡ, ân xá muôn loài.',
    poem: 'Sấm dậy mưa tuôn giải hạn hè / Muôn cây xanh ngát đón ngày hoe / Nguy nan đã dứt đường quang đãng / Khúc hát thanh bình vọng tiếng ve.',
    advice: 'Bỏ qua chuyện cũ, khoan dung tha thứ và nhanh chóng nắm bắt cơ hội mới.',
    domains: {
      taiLoc: 'Các khoản nợ được giải quyết, tiền bạc hanh thông trở lại.',
      congDanh: 'Áp lực công việc được tháo gỡ, dự án được thông qua thuận lợi.',
      giaDao: 'Mâu thuẫn được giải tỏa, không khí gia đình nhẹ nhõm vui vẻ.',
      sucKhoe: 'Bệnh tật tiêu tan, cơ thể hồi phục nhanh chóng.',
    },
  },
  {
    id: 41,
    name: 'Sơn Trạch Tổn',
    nature: 'Sơn Trạch Tổn',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Bớt dưới thêm trên, chịu thiệt thòi trước mắt để đổi lấy phúc lộc lâu dài.',
    poem: 'Khoét đầm bồi núi dẫu hao mòn / Tâm thiện vì đời dạ sắt son / Nhịn chút lợi riêng nuôi phúc lớn / Mai này con cháu hưởng vuông tròn.',
    advice: 'Chấp nhận hy sinh cái nhỏ vì đại cục, chân thành giúp đỡ người khác.',
    domains: {
      taiLoc: 'Tốn kém chi phí ban đầu nhưng là đầu tư sinh lời về sau.',
      congDanh: 'Chịu nhường nhịn một bước để sau này tiến xa ba bước.',
      giaDao: 'Mỗi người bớt cái tôi một chút thì gia đình êm ấm.',
      sucKhoe: 'Hạn chế ăn đồ ngọt và chất béo, thanh lọc cơ thể.',
    },
  },
  {
    id: 42,
    name: 'Phong Lôi Ích',
    nature: 'Phong Lôi Ích',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Gió sấm cùng tăng cường sức mạnh, tăng ích lợi, thấy điều thiện thì làm ngay.',
    poem: 'Gió thổi sấm vang ích nước non / Phúc lành ban phát dạ vàng son / Mở mang sự nghiệp muôn phương rạng / Hưởng trọn vinh hoa phúc cháu con.',
    advice: 'Thời vận đại lợi để đầu tư mở rộng, hãy tích cực làm việc thiện giúp đời.',
    domains: {
      taiLoc: 'Lợi nhuận tăng vọt, kinh doanh thuận buồm xuôi gió, tiền tài vào như nước.',
      congDanh: 'Được cất nhắc lên vị trí cao hơn, tiếng tăm lừng lẫy.',
      giaDao: 'Gia đình thịnh vượng, thêm người thêm của, ngập tràn hạnh phúc.',
      sucKhoe: 'Sức khỏe cường tráng, năng lượng tràn đầy.',
    },
  },
  {
    id: 43,
    name: 'Trạch Thiên Quải',
    nature: 'Trạch Thiên Quải',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Càn (Trời)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Nước đầm bốc lên trời sắp vỡ bờ, dứt khoát trừ bỏ kẻ xấu nhưng chớ dùng vũ lực.',
    poem: 'Đầm dâng ngập lối phải dời chân / Quyết đoán trừ tà giữ đức nhân / Minh bạch công tâm bày sự thật / Mới mong giữ vẹn chữ an thân.',
    advice: 'Cương quyết xử lý dứt điểm các vướng mắc, hành động công khai và minh bạch.',
    domains: {
      taiLoc: 'Cắt lỗ dứt khoát các khoản đầu tư rủi ro, bảo vệ tài sản chính.',
      congDanh: 'Thẳng thắn bày tỏ quan điểm, loại bỏ các nhân tố độc hại trong nhóm.',
      giaDao: 'Giải quyết triệt để chuyện nhập nhằng trong gia đình.',
      sucKhoe: 'Đề phòng huyết áp cao, cần kiểm tra định kỳ.',
    },
  },
  {
    id: 44,
    name: 'Thiên Phong Cấu',
    nature: 'Thiên Phong Cấu',
    upperTrigram: 'Càn (Trời)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Gió thổi dưới gầm trời, duyên tao ngộ bất ngờ, chớ để cám dỗ làm mờ lý trí.',
    poem: 'Gió thoảng chân mây gặp gỡ tình / Duyên kỳ ngộ đến chớ say sình / Đề phòng quyến rũ vương điều dối / Tỉnh táo giữ gìn nếp hiển vinh.',
    advice: 'Thận trọng trước những lời chào mời ngon ngọt hoặc cơ hội bất ngờ.',
    domains: {
      taiLoc: 'Đề phòng bẫy tài chính đội lốt cơ hội làm giàu nhanh.',
      congDanh: 'Gặp gỡ đối tác mới nhưng cần thẩm định kỹ uy tín trước khi ký kết.',
      giaDao: 'Cẩn thận người ngoài xen vào gây xáo trộn tình cảm gia đình.',
      sucKhoe: 'Cẩn thận các bệnh lây nhiễm qua đường hô hấp hoặc tiếp xúc.',
    },
  },
  {
    id: 45,
    name: 'Trạch Địa Tụy',
    nature: 'Trạch Địa Tụy',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Khôn (Đất)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Nước tụ trên mặt đất, người tụ họp đông đảo, chung lòng thờ kính tổ tiên.',
    poem: 'Đầm tụ trên đồng ngát sắc hương / Muôn người tụ hội khắp muôn phương / Lòng thành kính cẩn dâng linh vị / Phúc lộc tràn trề rạng đế vương.',
    advice: 'Tập hợp nhân tài, phát huy sức mạnh đoàn kết tập thể.',
    domains: {
      taiLoc: 'Kinh doanh dịch vụ, tổ chức sự kiện hoặc bán buôn thu lợi lớn.',
      congDanh: 'Có tài quy tụ lòng người, được tập thể tôn vinh làm thủ lĩnh.',
      giaDao: 'Họ hàng sum họp đầm ấm, giỗ chạp linh đình đoàn kết.',
      sucKhoe: 'Sức khỏe tốt, tinh thần vui vẻ khi sống trong tập thể hòa đồng.',
    },
  },
  {
    id: 46,
    name: 'Địa Phong Thăng',
    nature: 'Địa Phong Thăng',
    upperTrigram: 'Khôn (Đất)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Cây mọc từ lòng đất vươn lên đón ánh sáng, từng bước thăng tiến vững vàng.',
    poem: 'Cây mầm đội đất vươn trời cao / Từng bước thăng hoa dạ tự hào / Gặp bạn tương tri dìu dắt lối / Công danh rực rỡ tựa trăng sao.',
    advice: 'Tự tin tiến bước, tìm kiếm sự bảo bọc của quý nhân phương Nam.',
    domains: {
      taiLoc: 'Tài chính tăng trưởng đều đặn, đầu tư dài hạn gặt hái quả ngọt.',
      congDanh: 'Thăng tiến từng bước vững chắc, được nâng đỡ lên vị trí cao.',
      giaDao: 'Con cháu học hành giỏi giang, tương lai rạng ngời.',
      sucKhoe: 'Khỏe mạnh, cơ thể dẻo dai phát triển tốt.',
    },
  },
  {
    id: 47,
    name: 'Trạch Thủy Khốn',
    nature: 'Trạch Thủy Khốn',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Nước chảy cạn dưới đáy đầm, cùng cực bế tắc, nói chẳng ai tin cần im lặng.',
    poem: 'Đầm cạn trơ bùn cá khát khao / Khốn cùng bế tắc nỗi thanh tao / Đừng phân bua mãi thêm vương nạn / Nhẫn chí chờ ngày nước dâng cao.',
    advice: 'Không nên thanh minh tranh cãi, hãy âm thầm rèn luyện qua nghịch cảnh.',
    domains: {
      taiLoc: 'Thiếu hụt tiền mặt, hạn mức cạn kiệt, cần tiết kiệm tối đa.',
      congDanh: 'Bị cô lập, nói lời không ai nghe, nên im lặng làm tốt việc mình.',
      giaDao: 'Gia đình chịu áp lực lớn, cần kiên trì bên nhau vượt khó.',
      sucKhoe: 'Mệt mỏi kiệt sức, cần bổ sung nước và nghỉ ngơi.',
    },
  },
  {
    id: 48,
    name: 'Thủy Phong Tỉnh',
    nature: 'Thủy Phong Tỉnh',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Gỗ múc nước giếng lên nuôi người, giếng nước ngàn năm không cạn nguồn.',
    poem: 'Giếng sâu nước mát tưới đồng xa / Năm tháng nuôi người vạn mái nhà / Giữ vẹn dây gàu chớ để đứt / Phúc lành chan chứa tựa bài ca.',
    advice: 'Nuôi dưỡng gốc rễ nội lực, giữ gìn phương pháp làm việc chuẩn mực.',
    domains: {
      taiLoc: 'Nguồn thu ổn định như nước giếng làng, chi tiêu bền vững.',
      congDanh: 'Vững vàng chuyên môn, là chỗ dựa tin cậy cho đồng nghiệp.',
      giaDao: 'Gia đình truyền thống êm ấm, tương thân tương ái.',
      sucKhoe: 'Uống đủ nước, chú ý giữ gìn vệ sinh nguồn nước sinh hoạt.',
    },
  },
  {
    id: 49,
    name: 'Trạch Hỏa Cách',
    nature: 'Trạch Hỏa Cách',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Lửa thiêu dưới đầm nước, cải cách đổi mới, bỏ cũ theo mới hợp lòng người.',
    poem: 'Lửa nước giao tranh cải tạo đời / Đổi thay nếp cũ sáng ngời ngời / Thuận theo lòng thế muôn người thuận / Nghiệp lớn vinh quang rực khắp nơi.',
    advice: 'Mạnh dạn đổi mới phương pháp, xóa bỏ định kiến cũ để đón làn gió mới.',
    domains: {
      taiLoc: 'Chuyển đổi mô hình kinh doanh hoặc công nghệ mang lại doanh thu lớn.',
      congDanh: 'Đổi mới sáng tạo được ghi nhận, có bước đột phá trong sự nghiệp.',
      giaDao: 'Thay đổi lối sống lành mạnh hơn, tân trang nhà cửa.',
      sucKhoe: 'Thay đổi thói quen sinh hoạt xấu, sức khỏe cải thiện rõ rệt.',
    },
  },
  {
    id: 50,
    name: 'Hỏa Phong Đỉnh',
    nature: 'Hỏa Phong Đỉnh',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Gió thổi lửa cháy dưới đỉnh đồng, nấu chín thức ăn, định chế vững vàng.',
    poem: 'Vạc báu đun sôi thức ngọc ngà / Hiền tài phụng sự khắp gần xa / Uy danh vững chãi ngôi vương nghiệp / Đức sáng ngàn thu rạng nước nhà.',
    advice: 'Trọng dụng người hiền, xây dựng quy chuẩn vững chắc, củng cố vị thế.',
    domains: {
      taiLoc: 'Tài chính thịnh vượng, nắm giữ tài sản có giá trị lớn và lâu bền.',
      congDanh: 'Đạt đỉnh cao uy tín và quyền lực, được trọng vọng như báu vật.',
      giaDao: 'Gia phong rạng rỡ, con cháu thành đạt làm rạng danh dòng họ.',
      sucKhoe: 'Thể lực an khang, chú ý chế độ ẩm thực dưỡng sinh.',
    },
  },
  {
    id: 51,
    name: 'Thuần Chấn',
    nature: 'Chấn Vi Lôi',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Chấn (Sấm)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Sấm vang dội trăm dặm, giật mình sợ hãi nhưng sau đó cười nói an nhiên.',
    poem: 'Sấm động kinh hoàng vạn dặm xa / Giật mình tỉnh giấc trước phong ba / Bình tâm giữ đạo không lay chuyển / Nụ cười rạng rỡ khắp muôn nhà.',
    advice: 'Không hoảng loạn trước biến cố bất ngờ, bình tĩnh đối phó sẽ an lành.',
    domains: {
      taiLoc: 'Có biến động ngắn hạn, cần giữ bình tĩnh chớ hoảng loạn bán tháo.',
      congDanh: 'Đối mặt với thử thách bất ngờ, cần giữ vững bản lĩnh lãnh đạo.',
      giaDao: 'Có tin bất ngờ xảy đến, cần cùng nhau chia sẻ để trấn an.',
      sucKhoe: 'Tránh hoảng loạn, giữ tim mạch và thần kinh ổn định.',
    },
  },
  {
    id: 52,
    name: 'Thuần Cấn',
    nature: 'Cấn Vi Sơn',
    upperTrigram: 'Cấn (Núi)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Núi chồng lên núi, dừng đúng chỗ đúng lúc, tâm an định không dao động.',
    poem: 'Núi biếc trùng trùng đứng lặng yên / Dừng chân đúng lúc dứt ưu phiền / Giữ tâm thanh tịnh như bàn thạch / Hưởng trọn an lành tựa cảnh tiên.',
    advice: 'Biết điểm dừng, kiểm soát dục vọng, giữ tâm tĩnh lặng trước sóng gió.',
    domains: {
      taiLoc: 'Nên duy trì hiện trạng, không nên mở rộng đầu tư lúc này.',
      congDanh: 'Làm tốt vị trí hiện tại, chưa nên nhảy việc hay đòi hỏi thăng chức.',
      giaDao: 'Bình yên ổn định, duy trì cuộc sống thường nhật êm ấm.',
      sucKhoe: 'Cần vận động nhẹ nhàng để tránh đau lưng mỏi gối.',
    },
  },
  {
    id: 53,
    name: 'Phong Sơn Tiệm',
    nature: 'Phong Sơn Tiệm',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Cây mọc trên núi lớn dần, chim nhạn bay về từng bước chắc chắn.',
    poem: 'Cây mọc sườn non lớn vững vàng / Nhạn bay từng bước tới thiên đàng / Duyên lành kết trái đường êm thuận / Phúc ấm trường tồn mãi chứa chan.',
    advice: 'Tiến bước tuần tự theo quy trình, không đốt cháy giai đoạn.',
    domains: {
      taiLoc: 'Lợi nhuận tăng dần đều đặn, tích tiểu thành đại.',
      congDanh: 'Thăng tiến theo lộ trình vững chắc, chuyên môn ngày càng sâu.',
      giaDao: 'Hôn nhân thành tựu theo đúng lễ nghi, tình cảm mặn nồng.',
      sucKhoe: 'Sức khỏe cải thiện dần dần nhờ kiên trì tập luyện.',
    },
  },
  {
    id: 54,
    name: 'Lôi Trạch Quy Muội',
    nature: 'Lôi Trạch Quy Muội',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'hung',
    omenLabel: 'Hung',
    meaning: 'Cô gái đi lấy chồng sai vị thế, hành động vội vã trái tự nhiên khó bền.',
    poem: 'Gả muội vội vàng chuốc nỗi đau / Trái duyên nghịch lối chẳng bền lâu / Cương nhu bất xứng vương cay đắng / Tỉnh táo quay đầu giải mối sầu.',
    advice: 'Chớ nóng vội trong các quyết định hệ trọng, tránh làm việc trái quy luật.',
    domains: {
      taiLoc: 'Dễ thua lỗ vì đầu tư theo cảm xúc nhất thời, cần suy xét kỹ.',
      congDanh: 'Dục tốc bất đạt, nhảy cóc quy trình dễ bị trả giá đắt.',
      giaDao: 'Chuyện tình cảm có phần lệch lạc, cần sự tỉnh táo và chín chắn.',
      sucKhoe: 'Chú ý sức khỏe sinh sản và phụ khoa.',
    },
  },
  {
    id: 55,
    name: 'Lôi Hỏa Phong',
    nature: 'Lôi Hỏa Phong',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'dai_cat',
    omenLabel: 'Đại Cát',
    meaning: 'Sấm chớp rực rỡ, thịnh vượng tột cùng, như mặt trời chiếu giữa trưa.',
    poem: 'Sấm động lửa soi sáng vạn phương / Cơ đồ rực rỡ khắp thương trường / Đỉnh cao thịnh vượng tâm khiêm tốn / Mới giữ phúc dày mãi ngát hương.',
    advice: 'Đang ở thời điểm thịnh vượng nhất, cần chuẩn bị phương án dự phòng khi thoái trào.',
    domains: {
      taiLoc: 'Tiền bạc dồi dào sung túc, kinh doanh đạt doanh số kỷ lục.',
      congDanh: 'Quyền lực và tầm ảnh hưởng đạt mức cao nhất trong sự nghiệp.',
      giaDao: 'Gia đình vinh hiển tột bậc, nhiều tin vui cùng đến.',
      sucKhoe: 'Năng lượng dồi dào, cần tránh thức khuya và làm việc quá độ.',
    },
  },
  {
    id: 56,
    name: 'Hỏa Sơn Lữ',
    nature: 'Hỏa Sơn Lữ',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Lửa cháy lướt qua núi, người khách tha hương, khiêm nhường nơi đất khách.',
    poem: 'Lửa lướt sườn non khách viễn phương / Tha hương lập nghiệp dặm trường trường / Khiêm cung cẩn trọng gìn thân phận / Bình định tai ương rạng sắc hương.',
    advice: 'Nơi đất khách quê người nên giữ mình khiêm tốn, hòa đồng với bản xứ.',
    domains: {
      taiLoc: 'Thích hợp cho việc xuất ngoại, kinh doanh du lịch, xuất nhập khẩu.',
      congDanh: 'Lập nghiệp xa quê hương có cơ hội thành công cao hơn.',
      giaDao: 'Có người thân đi xa hoặc gia đình chuyển đổi chỗ ở.',
      sucKhoe: 'Chú ý an toàn khi di chuyển, cẩn thận dị ứng thời tiết.',
    },
  },
  {
    id: 57,
    name: 'Thuần Tốn',
    nature: 'Tốn Vi Phong',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Tốn (Gió)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Gió thổi thuận chiều liên tục, mềm mại len lỏi, cảm hóa lòng người.',
    poem: 'Gió thổi muôn phương nhẹ chuyển vần / Thuận theo thời thế giữ lòng nhân / Thâm sâu kín đáo len bờ cõi / Nghiệp cả hanh thông rạng thế trần.',
    advice: 'Dùng sự mềm mỏng, nhẫn nại để thuyết phục người khác, không áp đặt thô bạo.',
    domains: {
      taiLoc: 'Nguồn thu nhập đến từ các hợp đồng dịch vụ và trung gian khéo léo.',
      congDanh: 'Được cấp trên tin dùng giao các công việc ngoại giao, đàm phán.',
      giaDao: 'Gia đình nhỏ nhẹ hòa thuận, đối xử tế nhị với nhau.',
      sucKhoe: 'Chú ý bệnh đau nhức cơ bắp do trúng gió, cảm mạo.',
    },
  },
  {
    id: 58,
    name: 'Thuần Đoài',
    nature: 'Đoài Vi Trạch',
    upperTrigram: 'Đoài (Đầm)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Hai đầm nước liền nhau cùng vui vẻ, bạn bè trao đổi học thuật chan hòa.',
    poem: 'Đầm nước liền nhau ánh nguyệt soi / Bạn bè trao đổi thấu muôn lời / Nụ cười rạng rỡ tan sầu muộn / Hưởng trọn niềm vui giữa cuộc đời.',
    advice: 'Chia sẻ niềm vui, học hỏi bạn bè, dùng lời nói chân thành khích lệ người khác.',
    domains: {
      taiLoc: 'Kiếm tiền từ tài ăn nói, tư vấn, thuyết trình, truyền thông.',
      congDanh: 'Tạo mối quan hệ bằng hữu tốt đẹp, được đồng nghiệp hỗ trợ.',
      giaDao: 'Nhà cửa rộn rã tiếng cười, đón tiếp nhiều bạn bè thân thiết.',
      sucKhoe: 'Cười nhiều giúp khỏe người, chú ý họng và răng miệng.',
    },
  },
  {
    id: 59,
    name: 'Phong Thủy Hoán',
    nature: 'Phong Thủy Hoán',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Gió thổi trên mặt nước làm tan biến mây mù ngăn cách, cứu nguy giải nạn.',
    poem: 'Gió lướt mặt hồ sóng tản tan / Xua tan ngăn cách dứt lo toan / Đồng tâm hiệp lực xây đền miếu / Khúc hát thanh bình vọng tiếng vang.',
    advice: 'Mở rộng tấm lòng, tha thứ chuyện cũ, giải tỏa ngăn cách giữa người với người.',
    domains: {
      taiLoc: 'Tiền bạc lưu thông giải phóng khỏi ứ đọng, xoay vòng vốn tốt.',
      congDanh: 'Hóa giải hiểu lầm trong công việc, tái lập trật tự mới.',
      giaDao: 'Khoảng cách giữa các thành viên được hàn gắn, vui vẻ trở lại.',
      sucKhoe: 'Khí huyết lưu thông, tinh thần nhẹ nhõm thanh thản.',
    },
  },
  {
    id: 60,
    name: 'Thủy Trạch Tiết',
    nature: 'Thủy Trạch Tiết',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Nước giữ trong đầm có chừng mực, tiết chế khuôn phép, vừa vặn thì bền lâu.',
    poem: 'Đầm sâu giữ nước đắp bờ ngăn / Tiết kiệm chừng mực dạ chớ băn / Giữ đúng khuôn cương điều độ sống / Phúc dày muôn thuở dứt gian truân.',
    advice: 'Sống có chừng mực, chi tiêu có kế hoạch, không buông thả thái quá.',
    domains: {
      taiLoc: 'Quản lý tài chính chặt chẽ, tiết kiệm giúp tích lũy của cải vững vàng.',
      congDanh: 'Hành xử đúng quy trình, tuân thủ kỷ luật cơ quan được đánh giá cao.',
      giaDao: 'Chi tiêu trong gia đình nền nếp, không hoang phí.',
      sucKhoe: 'Ăn uống kiêng khem đúng mức, tránh ăn quá no hoặc thức quá khuya.',
    },
  },
  {
    id: 61,
    name: 'Phong Trạch Trung Phu',
    nature: 'Phong Trạch Trung Phu',
    upperTrigram: 'Tốn (Gió)',
    lowerTrigram: 'Đoài (Đầm)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Gió thổi trên đầm nước, lòng thành tín từ trong tâm cảm hóa được cả muông thú.',
    poem: 'Gió lướt mặt hồ sóng khẽ reo / Lòng thành cảm hóa vượt gieo neo / Tín nghĩa sáng soi ngàn vạn dặm / Phúc lộc tràn trề tựa trăng treo.',
    advice: 'Lấy chữ Tín làm đầu, giữ trọn lời hứa, đối đãi bằng tấm lòng chân thực.',
    domains: {
      taiLoc: 'Kinh doanh uy tín thu hút khách hàng trung thành, phát triển lâu bền.',
      congDanh: 'Được cấp trên và đối tác tuyệt đối tin cậy giao phó trọng sự.',
      giaDao: 'Vợ chồng tin tưởng lẫn nhau, gia đình thuận hòa hạnh phúc.',
      sucKhoe: 'Tâm tính hiền hòa giúp tinh thần an lạc, thân thể khỏe khoắn.',
    },
  },
  {
    id: 62,
    name: 'Lôi Sơn Tiểu Quá',
    nature: 'Lôi Sơn Tiểu Quá',
    upperTrigram: 'Chấn (Sấm)',
    lowerTrigram: 'Cấn (Núi)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Sấm trên núi, vượt qua chút ít trong khuôn khổ, việc nhỏ nên làm việc lớn chưa vội.',
    poem: 'Sấm dậy đầu non cánh nhạn bay / Vượt qua đôi chút chớ vung tay / Việc con gắng sức nên chu tất / Đại sự chờ thời định hướng nay.',
    advice: 'Làm tốt những việc nhỏ thường ngày, không nên mạo hiểm làm việc đại sự.',
    domains: {
      taiLoc: 'Thu lợi nhuận từ các giao dịch nhỏ, tránh đầu tư quy mô lớn.',
      congDanh: 'Chăm chút tỉ mỉ cho từng chi tiết công việc, tránh sai sót nhỏ.',
      giaDao: 'Nhường nhịn một chút trong sinh hoạt hàng ngày để giữ hòa khí.',
      sucKhoe: 'Chú ý an toàn khi đi lại vùng đồi núi, cẩn thận trượt ngã.',
    },
  },
  {
    id: 63,
    name: 'Thủy Hỏa Ký Tế',
    nature: 'Thủy Hỏa Ký Tế',
    upperTrigram: 'Khảm (Nước)',
    lowerTrigram: 'Ly (Lửa)',
    omen: 'cat',
    omenLabel: 'Cát',
    meaning: 'Nước trên lửa dưới, việc đã thành tựu viên mãn, cần giữ gìn để phòng thoái suy.',
    poem: 'Nước lửa điều hòa việc đã xong / Thuyền qua sóng gió cập bến trong / Thành công giữ vững tâm khiêm cẩn / Phòng buổi suy vi giữa sắc hồng.',
    advice: 'Công việc đã thành công, cần giữ gìn thành quả và cẩn trọng duy trì kỷ cương.',
    domains: {
      taiLoc: 'Thu hoạch lợi nhuận trọn vẹn, cần tái cơ cấu và bảo toàn vốn.',
      congDanh: 'Hoàn thành xuất sắc mục tiêu đề ra, được khen thưởng xứng đáng.',
      giaDao: 'Mọi việc yên ổn tốt lành, gia đình thịnh vượng no đủ.',
      sucKhoe: 'Thể chất cân bằng, âm dương hài hòa, sức khỏe tốt.',
    },
  },
  {
    id: 64,
    name: 'Hỏa Thủy Vị Tế',
    nature: 'Hỏa Thủy Vị Tế',
    upperTrigram: 'Ly (Lửa)',
    lowerTrigram: 'Khảm (Nước)',
    omen: 'binh',
    omenLabel: 'Bình Hòa',
    meaning: 'Lửa trên nước dưới chưa tương giao, việc chưa xong, tiếp tục nỗ lực sẽ thành công.',
    poem: 'Lửa trên nước dưới chửa giao hòa / Việc dẫu chưa xong chớ thở ra / Tiếp tục kiên tâm chèo lái vững / Bến bờ hạnh phúc đợi gần xa.',
    advice: 'Chưa phải lúc nghỉ ngơi, hãy tiếp tục nỗ lực hoàn thiện nốt chặng đường cuối.',
    domains: {
      taiLoc: 'Tiền bạc sắp về tài khoản, cần hoàn tất nốt các thủ tục giấy tờ.',
      congDanh: 'Dự án bước vào giai đoạn nước rút, cần tập trung cao độ.',
      giaDao: 'Còn vài việc nhỏ cần giải quyết dứt điểm để gia đạo hoàn toàn yên vui.',
      sucKhoe: 'Giữ gìn sức lực cho chặng đường cuối, không nên chủ quan.',
    },
  },
] as const;

export const chuVanVuongMethodSchema = z.enum(['coins', 'numbers', 'manual']);
export type ChuVanVuongMethod = z.infer<typeof chuVanVuongMethodSchema>;

export const chuVanVuongDrawSchema = z.object({
  question: z.string().min(1),
  method: chuVanVuongMethodSchema,
  hexagram: chuVanVuongHexagramSchema,
  narrative: z.string().min(1),
  coins: z.array(z.number().int().min(0).max(3)).length(6).optional(),
  numbers: z.tuple([z.number().int(), z.number().int()]).optional(),
  timestamp: z.string().optional(),
});

export type ChuVanVuongDraw = z.infer<typeof chuVanVuongDrawSchema>;

export const chuVanVuongDrawRequestSchema = z.object({
  question: z
    .string()
    .min(1, 'Câu hỏi gieo quẻ không được để trống.')
    .max(300, 'Câu hỏi tối đa 300 ký tự.'),
  method: chuVanVuongMethodSchema.default('coins'),
  hexagramId: z.number().int().min(1).max(64).optional(),
  numbers: z.tuple([z.number().int(), z.number().int()]).optional(),
  coins: z.array(z.number().int().min(0).max(3)).length(6).optional(),
});

export type ChuVanVuongDrawRequest = z.infer<typeof chuVanVuongDrawRequestSchema>;
